import type { Thread } from "@workspace/shared"
import type { DocumentService } from "../documents/document-service.js"
import type { Repositories } from "../repositories/index.js"

const DOCUMENT_PROMPT_PATTERN = /document|brief|report|notes|playbook/i

function wantsGeneratedDocument(prompt: string): boolean {
  return DOCUMENT_PROMPT_PATTERN.test(prompt)
}

function wantsDocumentUpdate(prompt: string): boolean {
  return (
    DOCUMENT_PROMPT_PATTERN.test(prompt) &&
    /update|append|revise|change|add/i.test(prompt)
  )
}

function wantsGlobalDocument(prompt: string): boolean {
  return /global|workspace-wide|workspace wide/i.test(prompt)
}

function requestedDocumentTitle(prompt: string): string | undefined {
  const quoted = prompt.match(/document (?:named|called) ["“]([^"”]+)["”]/i)
  return quoted?.[1]?.trim()
}

function mockDocumentSearchQuery(input: {
  prompt: string
  requestedTitle?: string
  globalDocument: boolean
}): string | undefined {
  if (input.requestedTitle) return input.requestedTitle
  if (input.globalDocument) return undefined
  return input.prompt
}

function mockDocumentTitle(input: {
  requestedTitle?: string
  globalDocument: boolean
}): string {
  if (input.requestedTitle) return input.requestedTitle
  return input.globalDocument ? "Global playbook" : "Project report"
}

export function createMockDocumentRunSuffix(input: {
  documentService: DocumentService
  repos: Repositories
  thread: Thread
  runId: string
  latestUserPrompt: string
}): string {
  if (!wantsGeneratedDocument(input.latestUserPrompt)) return ""

  const runContext = {
    threadId: input.thread.id,
    projectId: input.thread.projectId ?? undefined,
    runId: input.runId,
  }
  const globalDocument = wantsGlobalDocument(input.latestUserPrompt)
  const requestedTitle = requestedDocumentTitle(input.latestUserPrompt)

  if (wantsDocumentUpdate(input.latestUserPrompt)) {
    const target = input.documentService
      .findDocuments({
        query: mockDocumentSearchQuery({
          prompt: input.latestUserPrompt,
          requestedTitle,
          globalDocument,
        }),
        runContext,
        limit: 10,
      })
      .find((document) => document.documentType === "markdown")
    const updated = target
      ? input.documentService.appendDocumentSection({
          documentId: target.id,
          heading: "Mock runtime update",
          content: `Updated from ${input.thread.title}: ${input.latestUserPrompt.trim()}`,
          changeSummary: "Updated by mock runtime",
          runContext,
        })
      : undefined

    if (updated?.ok) {
      input.repos.steps.create({
        runId: input.runId,
        type: "tool-result",
        status: "completed",
        title: `Appended document section: ${updated.document.title}`,
        payload: {
          documentId: updated.document.id,
          title: updated.document.title,
          previousVersion: updated.previousVersion,
          currentVersion: updated.currentVersion,
        },
      })
      return `\n\nUpdated document **${updated.document.title}** to version ${updated.currentVersion}. View it in the Library.`
    }
  }

  const title = mockDocumentTitle({ requestedTitle, globalDocument })
  const generated = input.documentService.registerGenerated({
    title,
    description: "Generated by mock runtime",
    filename: `${title.toLowerCase().replace(/\s+/g, "-")}.md`,
    content: `# ${title}\n\n## Notes\n\n${input.latestUserPrompt.trim()}\n\nGenerated for ${input.thread.title}.`,
    visibilityScope: globalDocument ? "global" : undefined,
    projectId: globalDocument ? undefined : (input.thread.projectId ?? undefined),
    threadId: input.thread.id,
    runId: input.runId,
  })
  if (!generated.ok) return ""

  input.repos.steps.create({
    runId: input.runId,
    type: "tool-result",
    status: "completed",
    title: `Document created: ${generated.document.title}`,
    payload: {
      documentId: generated.document.id,
      title: generated.document.title,
      visibilityScope: generated.document.visibilityScope,
      currentVersion: generated.currentVersion,
    },
  })
  return `\n\nCreated document **${generated.document.title}** (id: ${generated.document.id}). View it in the Library.`
}
