#!/usr/bin/env node

/**
 * concat-md.js
 * 
 * Script to concatenate all markdown files in a directory into a single file
 * 
 * Usage:
 *   node concat-md.js <directory_path>
 */

const fs = require('fs');
const path = require('path');

// Check if directory path is provided
if (process.argv.length < 3) {
  console.error('Error: Please provide a directory path');
  console.log('Usage: node concat-md.js <directory_path>');
  process.exit(1);
}

// Get the directory path from command line arguments
const directoryPath = process.argv[2];

// Validate directory existence
if (!fs.existsSync(directoryPath)) {
  console.error(`Error: Directory "${directoryPath}" does not exist`);
  process.exit(1);
}

// Check if the path is a directory
const stats = fs.statSync(directoryPath);
if (!stats.isDirectory()) {
  console.error(`Error: "${directoryPath}" is not a directory`);
  process.exit(1);
}

// Extract directory name for the output file name
const dirName = path.basename(directoryPath);
const outputFileName = `_FULL-${dirName}.md`;
const outputFilePath = path.join(directoryPath, outputFileName);

// Read all markdown files in the directory
try {
  console.log(`Scanning directory: ${directoryPath}`);
  
  // Get all files in the directory
  const files = fs.readdirSync(directoryPath);
  
  // Filter for markdown files, excluding the output file itself
  const markdownFiles = files.filter(file => 
    file.endsWith('.md') && 
    file !== outputFileName && 
    !file.startsWith('_FULL-')
  );
  
  if (markdownFiles.length === 0) {
    console.log('No markdown files found in the directory');
    process.exit(0);
  }
  
  console.log(`Found ${markdownFiles.length} markdown files`);
  
  // Sort files alphabetically
  markdownFiles.sort();
  
  // Create a string to store the concatenated content
  let concatenatedContent = `# Combined Markdown Documentation: ${dirName}\n\n`;
  concatenatedContent += `*This file was automatically generated by concat-md.js on ${new Date().toISOString().split('T')[0]}*\n\n`;
  concatenatedContent += `*Contains the combined content of ${markdownFiles.length} markdown files from \`${directoryPath}\`*\n\n`;
  concatenatedContent += '---\n\n';
  
  // Table of Contents
  concatenatedContent += '## Table of Contents\n\n';
  for (let i = 0; i < markdownFiles.length; i++) {
    const fileName = markdownFiles[i];
    concatenatedContent += `${i+1}. [${fileName}](#${fileName.toLowerCase().replace(/\.md$/, '').replace(/[^a-z0-9]+/g, '-')})\n`;
  }
  concatenatedContent += '\n---\n\n';
  
  // Concatenate all markdown files
  for (const file of markdownFiles) {
    const filePath = path.join(directoryPath, file);
    const content = fs.readFileSync(filePath, 'utf8');
    
    // Add file header and content
    concatenatedContent += `## ${file}\n\n`;
    concatenatedContent += content;
    
    // Add separator between files
    concatenatedContent += '\n\n---\n\n';
  }
  
  // Write the concatenated content to the output file
  fs.writeFileSync(outputFilePath, concatenatedContent);
  
  console.log(`Successfully created: ${outputFilePath}`);
} catch (err) {
  console.error(`Error: ${err.message}`);
  process.exit(1);
}